INSERT INTO ROLE (ID, NAME) VALUES (1, 'Admin')

INSERT INTO CATEGORY (ID, DESCRIPTION, NAME) VALUES (1, '', 'Besuch')
INSERT INTO CATEGORY (ID, DESCRIPTION, NAME) VALUES (2, '', 'Veranstaltung')
INSERT INTO CATEGORY (ID, DESCRIPTION, NAME) VALUES (3, '', 'Termin')
